name: Ironman challenge lighthouse-ci demo
on: [push]
jobs:
  lhci:
    name: Lighthouse CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16.17.1
      - name: npm install, build
        run: |
          npm install
      - name: run lighthouse-ci
        run: |
          npm install -g @lhci/cli
          lhci autorun --upload.target=temporary-public-storage || echo "LHCI failed!"
        env:
          LHCI_GITHUB_APP_TOKEN: ${{secrets.LIGHTHOUSE_CI}}
